version: '2'
services:
  # Database
  mysql:
    image: mysql:5.7
    volumes:
      - "./data:/var/lib/mysql"
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: resto
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_PASSWORD: 1234
      PMA_USER: admin
      PMA_HOSTS: mysql
volumes:
  db_data:
      

